(() => {
  const data = window.PREVIEW;
  const root = document.getElementById('app');
  const state = {category:'Tümü', query:'', selected:null, cart:[]};
  const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  root.innerHTML = `
    <div class="shell">
      <header class="topbar"><div class="brand"><span class="mark">${escape(data.brand[0])}</span>${escape(data.brand)}</div><div class="top-actions"><span class="preview-pill">TASARIM DEMOSU · ÖDEME KAPALI</span><button class="cart-button" id="cartOpen">Sepet <strong id="cartCount">0</strong></button></div></header>
      <section class="hero"><div><div class="eyebrow">${escape(data.eyebrow)}</div><h1>${escape(data.headline)}</h1><p>${escape(data.subline)}</p><div class="hero-facts"><span>Şeffaf fiyat</span><span>Ürüne özel teslimat</span><span>Canlı destek</span></div></div><div class="hero-art"><div class="orb"></div></div></section>
      <div class="toolbar"><div><h2>Ürünleri keşfedin</h2><p>İhtiyacınıza uygun ürünü filtreleyin ve detaylarını açın.</p></div><input class="search" id="search" type="search" placeholder="Ürün veya kategori ara…" aria-label="Ürün ara"></div>
      <div class="filters" id="filters"></div><main class="grid" id="grid"></main>
      <p class="footnote">Bu sayfa yalnız tasarım önizlemesidir. Fiyat ve koşullar mevcut yerel katalogdan alınmıştır; ödeme işlemi yapılmaz.</p>
    </div>
    <div class="overlay" id="overlay" role="dialog" aria-modal="true" aria-label="Ürün detayları"><div class="dialog"><button class="close" id="modalClose" aria-label="Kapat">×</button><div id="modalContent"></div></div></div>
    <aside class="cart-panel" id="cartPanel" aria-label="Demo sepet"><button class="close" id="cartClose" aria-label="Kapat">×</button><h2>Demo sepet</h2><div id="cartItems"></div><div class="cart-total"><span>Toplam</span><span id="cartTotal">0,00 TL</span></div><button class="primary" id="checkout">Satın alma adımını gör</button><p class="footnote">Demo olduğu için gerçek ödeme bağlantısı açılmaz.</p></aside><div class="toast" id="toast"></div>`;
  const byId = id => document.getElementById(id);
  const money = value => Number(String(value).replace(' TL','').replace('.','').replace(',','.'));
  const cover = p => `<div class="demo-cover" aria-label="${escape(p.title)} ilan önizlemesi"><span class="cover-brand">${escape(data.brand)}</span><span class="cover-category">${escape(p.category)}</span><strong>${escape(p.title)}</strong><span class="cover-variant">${escape(p.variant)}</span><span class="cover-price">${escape(p.price)}</span></div>`;
  const showToast = message => {const el=byId('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)};
  const categories = ['Tümü', ...new Set(data.products.map(p => p.category))];
  function renderFilters(){byId('filters').innerHTML=categories.map(cat=>`<button class="filter ${state.category===cat?'active':''}" data-category="${escape(cat)}">${escape(cat)}</button>`).join('');byId('filters').querySelectorAll('button').forEach(btn=>btn.onclick=()=>{state.category=btn.dataset.category;renderFilters();renderGrid()})}
  function renderGrid(){const q=state.query.toLocaleLowerCase('tr');const products=data.products.filter(p=>(state.category==='Tümü'||p.category===state.category)&&`${p.title} ${p.variant} ${p.category}`.toLocaleLowerCase('tr').includes(q));byId('grid').innerHTML=products.map(p=>`<article class="product">${cover(p)}<div class="product-info"><span class="category">${escape(p.category)}</span><h3>${escape(p.title)}</h3><span class="variant">${escape(p.variant)}</span><div class="product-bottom"><span class="price">${escape(p.price)}</span><button class="detail-button" data-detail="${escape(p.id)}">Detay</button></div></div></article>`).join('')||'<p>Bu arama için ürün bulunamadı.</p>';byId('grid').querySelectorAll('[data-detail]').forEach(btn=>btn.onclick=()=>openDetail(btn.dataset.detail))}
  function openDetail(id){const p=data.products.find(x=>x.id===id);if(!p)return;state.selected=p;byId('modalContent').innerHTML=`<div class="dialog-body">${cover(p)}<div><span class="category">${escape(p.category)}</span><h2>${escape(p.title)}</h2><p>${escape(p.note)}</p><div class="facts"><div class="fact"><span>Ürün türü</span><strong>${escape(p.variant)}</strong></div><div class="fact"><span>Teslimat</span><strong>${escape(p.delivery)}</strong></div><div class="fact"><span>Garanti</span><strong>${escape(p.warranty)}</strong></div><div class="fact"><span>Fiyat</span><strong>${escape(p.price)}</strong></div></div><div class="dialog-actions"><button class="primary" id="addCart">Sepete ekle</button><button class="secondary" id="previewBuy">Satın alma adımını gör</button></div></div></div>`;byId('addCart').onclick=()=>{state.cart.push(p);byId('overlay').classList.remove('open');renderCart();showToast('Ürün demo sepetine eklendi')};byId('previewBuy').onclick=()=>showToast('Ödeme demo sürümünde kapalıdır');byId('overlay').classList.add('open')}
  function renderCart(){byId('cartCount').textContent=state.cart.length;byId('cartItems').innerHTML=state.cart.length?state.cart.map(p=>`<div class="cart-row"><div><strong>${escape(p.title)}</strong><small>${escape(p.variant)}</small></div><strong>${escape(p.price)}</strong></div>`).join(''):'<p>Sepetiniz boş. Ürün kartından ekleyebilirsiniz.</p>';byId('cartTotal').textContent=state.cart.reduce((sum,p)=>sum+money(p.price),0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})+' TL'}
  byId('search').oninput=e=>{state.query=e.target.value;renderGrid()};byId('modalClose').onclick=()=>byId('overlay').classList.remove('open');byId('overlay').onclick=e=>{if(e.target.id==='overlay')byId('overlay').classList.remove('open')};byId('cartOpen').onclick=()=>byId('cartPanel').classList.add('open');byId('cartClose').onclick=()=>byId('cartPanel').classList.remove('open');byId('checkout').onclick=()=>showToast('Ödeme demo sürümünde kapalıdır');document.onkeydown=e=>{if(e.key==='Escape'){byId('overlay').classList.remove('open');byId('cartPanel').classList.remove('open')}};renderFilters();renderGrid();renderCart();
})();
