#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
LisansArena Master Catalog Builder & Clean 3D Card Mapper
1. Deduplicates products (removes exact duplicates).
2. Fixes Turkish characters (UTF-8).
3. Orders Vitrin (Showcase) exactly as requested:
   - 1000 Takipçi
   - Canva Pro
   - Netflix
   - YouTube
   - Spotify
   - Exxen
   - Gemini Davet
   - CapCut Pro
   - Steam Ürünleri
4. Maps 100% clean, non-robotic, high-aesthetic 3D product cards.
"""

import os
import json
import shutil
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
LA_DIR = BASE_DIR / "miniapp_lisansarena"
LA_ASSETS = LA_DIR / "assets" / "products"
LA_ASSETS.mkdir(parents=True, exist_ok=True)

ART_DIR_1 = Path("C:/Users/habil/.gemini/antigravity/brain/b3d6b142-698f-408f-8efb-52bc1b303e13")
ART_DIR_2 = Path("C:/Users/habil/.gemini/antigravity/brain/fbd09d2b-4007-40b6-be24-bbd2f7ab73dc")

def find_art(filename_pattern):
    for d in (ART_DIR_2, ART_DIR_1):
        if d.exists():
            matches = list(d.glob(filename_pattern))
            if matches:
                matches.sort(key=lambda x: x.stat().st_mtime, reverse=True)
                return matches[0]
    return None

ART_MAP = {
    "instagram": find_art("instagram_followers_card_*.jpg") or find_art("la_ai_instagram_followers.jpg"),
    "canva": find_art("canva_pro_card_*.jpg") or find_art("kv_canva_ai_*.jpg"),
    "netflix": find_art("netflix_4k_card_*.jpg") or find_art("kv_netflix_ai_*.jpg"),
    "youtube": find_art("youtube_premium_card_*.jpg") or find_art("kv_youtube_ai_*.jpg"),
    "spotify": find_art("spotify_premium_card_*.jpg") or find_art("kv_spotify_ai_*.jpg"),
    "exxen": find_art("exxen_reklamsiz_card_*.jpg") or find_art("kv_exxen_ai_*.jpg"),
    "gemini": find_art("kv_gemini_ai_*.jpg") or find_art("gemini_ultra_3d_*.jpg"),
    "capcut": find_art("capcut_pro_card_*.jpg") or find_art("kv_capcut_ai_*.jpg"),
    "steam": find_art("steam_random_card_*.jpg") or find_art("kv_steam_ai_*.jpg"),
    "steam_game": find_art("la_steam_game_ai_*.jpg") or find_art("steam_random_card_*.jpg"),
    "fc26": find_art("kv_fc26_ai_*.jpg") or find_art("fc26_listing_*.jpg"),
    "grok": find_art("kv_grok_ai_*.jpg") or find_art("grok_listing_*.jpg"),
    "perplexity": find_art("la_perplexity_ai_*.jpg"),
    "gamma": find_art("la_gamma_ai_*.jpg"),
    "deepl": find_art("la_deepl_ai_*.jpg"),
    "duolingo": find_art("la_duolingo_ai_*.jpg"),
    "scribd": find_art("la_scribd_ai_*.jpg"),
    "magnific": find_art("la_magnific_ai_*.jpg"),
    "grammarly": find_art("la_grammarly_ai_*.jpg"),
    "crunchyroll": find_art("la_crunchyroll_ai_*.jpg"),
    "prime": find_art("prime_video_card_*.jpg"),
    "hbo": find_art("hbo_max_card_*.jpg") or find_art("hbo_max_listing_*.jpg"),
    "envato": find_art("envato_elements_card_*.jpg"),
    "freepik": find_art("freepik_premium_card_*.jpg"),
    "adobe": find_art("adobe_creative_card_*.jpg") or find_art("kv_adobe_ai_*.jpg"),
    "office": find_art("office365_card_*.jpg") or find_art("windows_office_listing_*.jpg"),
    "windows": find_art("windows_pro_card_*.jpg") or find_art("kv_windows_ai_*.jpg"),
    "minecraft": find_art("minecraft_capes_card_*.jpg"),
    "roblox": find_art("roblox_offsale_card_*.jpg"),
    "gmail": find_art("gmail_account_card_*.jpg"),
    "telegram": find_art("kv_telegram_ai_*.jpg") or find_art("telegram_account_listing_*.jpg"),
    "shell": find_art("la_shell_fuel_ai_*.jpg") or find_art("kv_trendyol_ai_*.jpg"),
    "zula": find_art("kv_zula_ai_*.jpg") or find_art("zula_listing_*.jpg"),
}

# Copy clean files to assets directory
copied_cache = {}
for key, src_path in ART_MAP.items():
    if src_path and src_path.exists():
        dest_filename = f"card_clean_{key}.jpg"
        dest_path = LA_ASSETS / dest_filename
        shutil.copy2(src_path, dest_path)
        copied_cache[key] = f"assets/products/{dest_filename}"
        print(f"[+] Clean Card Installed: {key} -> {dest_filename}")

# Raw product definitions with clean Turkish metadata & unique Shopier IDs
RAW_CATALOG = [
    # --- 1. VITRIN / SHOWCASE PRIMARY ITEMS (User Explicit Sequence) ---
    {
        "id": "la_ig_1000",
        "title": "Instagram 1000 Takipçi (30 Gün Telafili & Düşmeyen)",
        "price": "49,90 TL",
        "category": "social",
        "is_vitrin": True,
        "showcase": True,
        "badge": "⚡ POPÜLER",
        "art_key": "instagram",
        "rating": 4.9,
        "sales_count": 1840,
        "delivery": "⚡ Otomatik Anında Başlar",
        "warranty": "🛡️ 30 Gün Telafi Garantisi",
        "desc": "Türk & Global karışık kaliteli aktif profiller. Şifre gerekmez, sadece kullanıcı adı yeterlidir. 30 gün telafi garantilidir.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "48973858",
        "title": "Canva Pro (1 Yıllık Yetki & Özel Lisans)",
        "price": "83,99 TL",
        "category": "design",
        "is_vitrin": True,
        "showcase": True,
        "badge": "💎 ÇOK SATAN",
        "art_key": "canva",
        "rating": 5.0,
        "sales_count": 2150,
        "delivery": "⚡ 7/24 Anında Teslimat",
        "warranty": "🛡️ 1 Yıl Değişim Garantili",
        "desc": "Kendi e-posta adresinize 1 yıllık Canva Pro lisansı tanımlanır. Tüm premium şablonlar, Magic Studio ve 1TB bulut alanı açıktır.",
        "shopier_url": "https://www.shopier.com/48973858"
    },
    {
        "id": "la_netflix_ozel",
        "title": "Netflix 4K UHD (Özel Kişisel Profil)",
        "price": "109,90 TL",
        "category": "cinema",
        "is_vitrin": True,
        "showcase": True,
        "badge": "🔥 4K ULTRA HD",
        "art_key": "netflix",
        "rating": 4.9,
        "sales_count": 3420,
        "delivery": "⚡ Anında Otomatik Teslimat",
        "warranty": "🛡️ 30 Gün Kesintisiz Garanti",
        "desc": "PIN korumalı tamamen size özel profil. 4K Ultra HD ve Spatial Audio desteği. Donma ve kapanma yapmaz.",
        "shopier_url": "https://www.shopier.com/49002144"
    },
    {
        "id": "la_youtube_3m",
        "title": "YouTube Premium (3 Aylık Lisans Kodu)",
        "price": "39,90 TL",
        "category": "social",
        "is_vitrin": True,
        "showcase": True,
        "badge": "⚡ ANINDA TESLİM",
        "art_key": "youtube",
        "rating": 4.9,
        "sales_count": 1650,
        "delivery": "⚡ Anında Kod Teslimi",
        "warranty": "🛡️ 3 Ay Garantili",
        "desc": "Reklamsız YouTube ve YouTube Music keyfi. Kendi Google hesabınızda geçerlidir. Arka planda oynatma ve çevrimdışı indirme.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_spotify_3m",
        "title": "Spotify Premium (3 Aylık Davet & Kod)",
        "price": "19,90 TL",
        "category": "social",
        "is_vitrin": True,
        "showcase": True,
        "badge": "🔥 İNDİRİMLİ",
        "art_key": "spotify",
        "rating": 4.8,
        "sales_count": 1420,
        "delivery": "⚡ Anında Kod Teslimi",
        "warranty": "🛡️ 3 Ay Birebir Garanti",
        "desc": "Kendi hesabınızda reklamsız, yüksek kaliteli ses ve sınırsız şarkı atlama. Çevrimdışı müzik indirme aktif.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_exxen_3m",
        "title": "Exxen Reklamsız (3 Aylık Lisans Kodu)",
        "price": "29,90 TL",
        "category": "cinema",
        "is_vitrin": True,
        "showcase": True,
        "badge": "⚡ SÜPER FİYAT",
        "art_key": "exxen",
        "rating": 4.7,
        "sales_count": 980,
        "delivery": "⚡ Kod Anında Ekranda",
        "warranty": "🛡️ 3 Ay Güvenceli",
        "desc": "Exxen tüm dizi, film ve programları reklamsız izleme kodu. Türkiye sunucuları uyumlu anında aktivasyon.",
        "shopier_url": "https://www.shopier.com/49002143"
    },
    {
        "id": "48945492",
        "title": "Gemini Pro Davet (12 Aylık Lisans)",
        "price": "99,99 TL",
        "category": "ai",
        "is_vitrin": True,
        "showcase": True,
        "badge": "🤖 GOOGLE AI",
        "art_key": "gemini",
        "rating": 4.9,
        "sales_count": 1540,
        "delivery": "⚡ 7/24 Anında Otomatik Davet",
        "warranty": "🛡️ 12 Ay Tam Garanti",
        "desc": "Google Gemini Pro 1.5 Pro modeli ile kendi Gmail hesabınıza 12 aylık Pro erişim tanımlama daveti.",
        "shopier_url": "https://www.shopier.com/48945492"
    },
    {
        "id": "48945487",
        "title": "Gemini Ultra (Davet Linki - 12 Aylık)",
        "price": "419,99 TL",
        "category": "ai",
        "is_vitrin": True,
        "showcase": True,
        "badge": "💎 EN GÜÇLÜ AI",
        "art_key": "gemini",
        "rating": 5.0,
        "sales_count": 870,
        "delivery": "⚡ Anında Davet Linki",
        "warranty": "🛡️ 1 Yıl Değişim Garantisi",
        "desc": "Google'ın en gelişmiş Gemini Ultra ve 2M Context Penceresi desteği. 2TB Google One Cloud alanı dahildir.",
        "shopier_url": "https://www.shopier.com/48945487"
    },
    {
        "id": "la_capcut_kisisel",
        "title": "CapCut Pro (1 Aylık Kişisel Lisans)",
        "price": "179,90 TL",
        "category": "design",
        "is_vitrin": True,
        "showcase": True,
        "badge": "🎬 VİDEO EDİT",
        "art_key": "capcut",
        "rating": 4.9,
        "sales_count": 1120,
        "delivery": "⚡ Anında Otomatik Teslimat",
        "warranty": "🛡️ 30 Gün Birebir Garanti",
        "desc": "PC ve Mobilde tüm premium AI efektleri, otomatik altyazı, 4K 60FPS export ve yeşil ekran araçları.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_steam_200",
        "title": "Steam 200$ Değerinde VIP Random Key",
        "price": "39,90 TL",
        "category": "gaming",
        "is_vitrin": True,
        "showcase": True,
        "badge": "🎮 VIP OYUN",
        "art_key": "steam",
        "rating": 4.8,
        "sales_count": 2890,
        "delivery": "⚡ Key Anında Ekrana Düşer",
        "warranty": "🛡️ Orijinal Steam Key Güvencesi",
        "desc": "Steam mağaza değeri 200$ ve üzeri olan garantili AAA / Popüler oyun lisans anahtarı. Sıfır boş key garantisi.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "48945475",
        "title": "Steam İstediğiniz Oyun (Ortak Hesap)",
        "price": "63,00 TL",
        "category": "gaming",
        "is_vitrin": True,
        "showcase": True,
        "badge": "🕹️ SEÇMELİ OYUN",
        "art_key": "steam_game",
        "rating": 4.8,
        "sales_count": 760,
        "delivery": "⚡ 7/24 Anında Teslimat",
        "warranty": "🛡️ Ömür Boyu Garanti",
        "desc": "Steam kütüphanesindeki dilediğiniz güncel popüler oyuna tam erişimli hesap. Hikaye modunu sınırsız oynayabilirsiniz.",
        "shopier_url": "https://www.shopier.com/48945475"
    },

    # --- 2. DİĞER POPÜLER & TEMİZ ÜRÜNLER (Kategorilerine Göre) ---
    {
        "id": "49099069",
        "title": "FC26 + Online Her Şeyi Değişen Hesap",
        "price": "299,99 TL",
        "category": "gaming",
        "is_vitrin": True,
        "showcase": True,
        "badge": "⚽ FUTBOL DEVİ",
        "art_key": "fc26",
        "rating": 4.9,
        "sales_count": 620,
        "delivery": "⚡ E-posta & Şifre Anında Teslim",
        "warranty": "🛡️ İlk Mail & Tam Garanti",
        "desc": "EA Sports FC 26 tam sürüm hesap. Mail, şifre ve güvenlik bilgileri tamamen üzerinize geçer. Online modlar açıktır.",
        "shopier_url": "https://www.shopier.com/49099069"
    },
    {
        "id": "49099022",
        "title": "Zula Random Hesap",
        "price": "5,00 TL",
        "category": "gaming",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🔫 FPS OYUN",
        "art_key": "zula",
        "rating": 4.5,
        "sales_count": 890,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ Giriş Garantili",
        "desc": "Silahlı, kasalı veya efsane desenli sürpriz Zula hesabı. Şansınıza göre yüksek rütbeli hesaplar çıkabilir.",
        "shopier_url": "https://www.shopier.com/49099022"
    },
    {
        "id": "49078922",
        "title": "Canva Pro Öğretmen (1 Yıllık Lisans)",
        "price": "149,99 TL",
        "category": "design",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🎓 ÖĞRETMEN PANELİ",
        "art_key": "canva",
        "rating": 4.9,
        "sales_count": 430,
        "delivery": "⚡ Anında Aktivasyon",
        "warranty": "🛡️ 1 Yıl Değişim Garantili",
        "desc": "Öğretmen yetkili 1 yıllık Canva Pro hesabı. 500 öğrenci ekleme yetkisi ve tam yetkili yönetim paneli.",
        "shopier_url": "https://www.shopier.com/49078922"
    },
    {
        "id": "la_canva_ogrenci",
        "title": "Canva Pro Öğrenci (1 Yıllık Lisans)",
        "price": "49,90 TL",
        "category": "design",
        "is_vitrin": False,
        "showcase": False,
        "badge": "📚 ÖĞRENCİ FIRSATI",
        "art_key": "canva",
        "rating": 4.8,
        "sales_count": 910,
        "delivery": "⚡ Anında Aktivasyon",
        "warranty": "🛡️ 1 Yıl Garanti",
        "desc": "1 Yıllık Canva Pro öğrenci lisansı. Kendi hesabınıza bağlanır, tüm Pro şablonlar ve yapay zeka araçları açıktır.",
        "shopier_url": "https://www.shopier.com/48973858"
    },
    {
        "id": "48945675",
        "title": "Shell 75 TL Akaryakıt Puanı",
        "price": "14,99 TL",
        "category": "coupons",
        "is_vitrin": False,
        "showcase": False,
        "badge": "⛽ YAKIT İNDİRİMİ",
        "art_key": "shell",
        "rating": 4.8,
        "sales_count": 1340,
        "delivery": "⚡ Kod Anında Ekranda",
        "warranty": "🛡️ Anında Kullanım Garantisi",
        "desc": "Shell istasyonlarında geçerli 75 TL değerinde ClubSmart akaryakıt puanı yükleme kodu.",
        "shopier_url": "https://www.shopier.com/48945675"
    },
    {
        "id": "48945493",
        "title": "Gemini Pro Premium Hesap (12 Aylık)",
        "price": "209,89 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "⭐ ÖZEL HESAP",
        "art_key": "gemini",
        "rating": 4.9,
        "sales_count": 680,
        "delivery": "⚡ Anında Hesap Bilgisi",
        "warranty": "🛡️ 1 Yıl Değişim Garantili",
        "desc": "Kullanıma hazır, 12 ay aktif Google Gemini Pro hesabı. Tüm Pro yapay zeka özellikleri ve yüksek token limiti açıktır.",
        "shopier_url": "https://www.shopier.com/48945493"
    },
    {
        "id": "48945489",
        "title": "Gemini Ultra (2.5k Kredili Hesap)",
        "price": "599,99 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "⚡ YÜKSEK KREDİ",
        "art_key": "gemini",
        "rating": 5.0,
        "sales_count": 310,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ Birebir Kredi Garantisi",
        "desc": "İçerisinde 2.500 API / Web kredisi yüklü Gemini Ultra hesabı. Geliştiriciler ve ağır veri analizi için idealdir.",
        "shopier_url": "https://www.shopier.com/48945489"
    },
    {
        "id": "48945485",
        "title": "Gamma Pro (1 Aylık Hesap)",
        "price": "299,99 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "📊 SUNUM AI",
        "art_key": "gamma",
        "rating": 4.8,
        "sales_count": 420,
        "delivery": "⚡ 7/24 Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Yapay zeka ile saniyeler içinde büyüleyici sunumlar ve web sayfaları hazırlayan Gamma Pro hesabı.",
        "shopier_url": "https://www.shopier.com/48945485"
    },
    {
        "id": "48945484",
        "title": "Gamma Ultra (1 Aylık Hesap)",
        "price": "472,49 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🚀 ULTRA SUNUM",
        "art_key": "gamma",
        "rating": 4.9,
        "sales_count": 210,
        "delivery": "⚡ Anında Teslimat",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Sınırsız AI kredi kullanımı, özel font yükleme ve gelişmiş analitik içeren en üst paket Gamma Ultra.",
        "shopier_url": "https://www.shopier.com/48945484"
    },
    {
        "id": "48945482",
        "title": "Super Grok (12 Aylık Hesap)",
        "price": "2.414,99 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "⚡ XAI YILLIK",
        "art_key": "grok",
        "rating": 5.0,
        "sales_count": 140,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 1 Yıl Garanti",
        "desc": "Elon Musk'ın xAI Grok 2 ve Grok 3 modellerine 12 ay kesintisiz sınırsız erişim sağlayan Premium hesap.",
        "shopier_url": "https://www.shopier.com/48945482"
    },
    {
        "id": "48945481",
        "title": "Super Grok (6 Aylık Hesap)",
        "price": "1.574,99 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "⚡ XAI 6 AY",
        "art_key": "grok",
        "rating": 4.9,
        "sales_count": 230,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 6 Ay Garanti",
        "desc": "6 Ay boyunca xAI Grok yapay zeka modellerine sansürsüz ve gerçek zamanlı Twitter/X verisiyle erişim.",
        "shopier_url": "https://www.shopier.com/48945481"
    },
    {
        "id": "48945480",
        "title": "Super Grok (3 Aylık Hesap)",
        "price": "997,49 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "⚡ XAI 3 AY",
        "art_key": "grok",
        "rating": 4.8,
        "sales_count": 390,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 3 Ay Garanti",
        "desc": "3 Aylık Super Grok hesabı. Kod yazma, analiz ve görsel üretimi (Flux 1) özelliklerini içerir.",
        "shopier_url": "https://www.shopier.com/48945480"
    },
    {
        "id": "48945476",
        "title": "Super Grok (1 Aylık Hesap)",
        "price": "472,49 TL",
        "category": "ai",
        "is_vitrin": True,
        "showcase": True,
        "badge": "⚡ XAI AYLIK",
        "art_key": "grok",
        "rating": 4.8,
        "sales_count": 820,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Birebir Garanti",
        "desc": "1 Aylık Super Grok hesabı. Gerçek zamanlı haber analizi ve sınırsız sorgulama imkanı.",
        "shopier_url": "https://www.shopier.com/48945476"
    },
    {
        "id": "48901878",
        "title": "Eski Tarihli Telegram Hesabı (+1 No'lu)",
        "price": "149,90 TL",
        "category": "social",
        "is_vitrin": True,
        "showcase": True,
        "badge": "📱 TEMİZ HESAP",
        "art_key": "telegram",
        "rating": 4.9,
        "sales_count": 1780,
        "delivery": "⚡ TData & Session Anında Teslim",
        "warranty": "🛡️ İlk Giriş ve Spam Garantili",
        "desc": "2020-2023 arası açılmış, temiz +1 Amerika numaralı eski tarihli Telegram hesabı. Reklam ve kanal yönetimi için ban riski minimumdur.",
        "shopier_url": "https://www.shopier.com/48901878"
    },
    {
        "id": "48901877",
        "title": "Perplexity Pro (1 Aylık Hesap)",
        "price": "119,90 TL",
        "category": "ai",
        "is_vitrin": True,
        "showcase": True,
        "badge": "🔍 AKILLI ARAMA",
        "art_key": "perplexity",
        "rating": 4.9,
        "sales_count": 1390,
        "delivery": "⚡ Anında Teslimat",
        "warranty": "🛡️ 30 Gün Değişim Garantisi",
        "desc": "GPT-4o, Claude 3.5 Sonnet ve Sonar modellerine sınırsız erişim. Akademik ve profesyonel araştırmalar için 1 numara.",
        "shopier_url": "https://www.shopier.com/48901877"
    },
    {
        "id": "48901876",
        "title": "Super Duolingo Sınırsız (Ortak Hesap)",
        "price": "49,90 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🦉 DİL ÖĞRENİMİ",
        "art_key": "duolingo",
        "rating": 4.8,
        "sales_count": 870,
        "delivery": "⚡ Anında Giriş Bilgileri",
        "warranty": "🛡️ 1 Yıl Garanti",
        "desc": "Sınırsız can, reklamsız öğrenme ve hata alıştırmaları. İstediğiniz dilde kesintisiz pratik yapın.",
        "shopier_url": "https://www.shopier.com/48901876"
    },
    {
        "id": "48901875",
        "title": "DeepL AI (1 Aylık) - Kişisel Hesap",
        "price": "59,90 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🌍 ÇEVİRİ DEVİ",
        "art_key": "deepl",
        "rating": 4.9,
        "sales_count": 640,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Dünyanın en iyi yapay zeka çeviri motoru DeepL Pro. Sınırsız metin ve tam doküman (PDF, Word) çevirisi.",
        "shopier_url": "https://www.shopier.com/48901875"
    },
    {
        "id": "48901874",
        "title": "DeepL AI (1 Aylık) - Ortak Hesap",
        "price": "29,90 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "⚡ UYGUN FİYAT",
        "art_key": "deepl",
        "rating": 4.7,
        "sales_count": 480,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Ekonomik DeepL Pro ortak hesabı. Hızlı ve doğal dille profesyonel makale ve metin çevirisi.",
        "shopier_url": "https://www.shopier.com/48901874"
    },
    {
        "id": "48901873",
        "title": "Scribd (1 Aylık) - Kişisel Hesap",
        "price": "59,90 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "📚 KİTAP & MAKALELER",
        "art_key": "scribd",
        "rating": 4.8,
        "sales_count": 510,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Milyonlarca e-kitap, sesli kitap, akademik makale ve podcast'e sınırsız erişim sağlayan Scribd hesabı.",
        "shopier_url": "https://www.shopier.com/48901873"
    },
    {
        "id": "48901872",
        "title": "Scribd (1 Aylık) - Ortak Hesap",
        "price": "29,90 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "📖 KÜTÜPHANE",
        "art_key": "scribd",
        "rating": 4.7,
        "sales_count": 390,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Ortak kullanımlı Scribd hesabı. E-kitapları ve sunumları sınırsız indirin.",
        "shopier_url": "https://www.shopier.com/48901872"
    },
    {
        "id": "48901869",
        "title": "Magnific AI Ortak (1 Aylık Business)",
        "price": "49,90 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🎨 8K UPSCALE",
        "art_key": "magnific",
        "rating": 4.9,
        "sales_count": 720,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Görselleri 8K ultra çözünürlüğe yükselten ve inanılmaz detaylar ekleyen Magnific AI Business hesabı.",
        "shopier_url": "https://www.shopier.com/48901869"
    },
    {
        "id": "48901859",
        "title": "Adobe Creative Cloud (1 Aylık) - Ortak Hesap",
        "price": "49,90 TL",
        "category": "design",
        "is_vitrin": True,
        "showcase": True,
        "badge": "🎨 TÜM ADOBE",
        "art_key": "adobe",
        "rating": 4.8,
        "sales_count": 1620,
        "delivery": "⚡ Anında Teslimat",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Photoshop, Illustrator, Premiere Pro, After Effects dahil 20+ Adobe masaüstü uygulaması.",
        "shopier_url": "https://www.shopier.com/48901859"
    },
    {
        "id": "48901858",
        "title": "Adobe Creative Cloud (1 Haftalık) - Kendi Hesabınıza",
        "price": "59,90 TL",
        "category": "design",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🚀 KİŞİSEL ADOBE",
        "art_key": "adobe",
        "rating": 4.9,
        "sales_count": 840,
        "delivery": "⚡ Anında Tanımlama",
        "warranty": "🛡️ Birebir Garanti",
        "desc": "Kendi Adobe hesabınıza 7 gün süreli tam yetkili Creative Cloud lisans tanımlaması.",
        "shopier_url": "https://www.shopier.com/48901858"
    },
    {
        "id": "48901857",
        "title": "Grammarly Pro (1 Aylık) - Ortak Hesap",
        "price": "49,90 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "✍️ YAZIM AI",
        "art_key": "grammarly",
        "rating": 4.8,
        "sales_count": 690,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "İngilizce metin ve makaleleriniz için dilbilgisi, tonlama ve yapay zeka yeniden yazım asistanı.",
        "shopier_url": "https://www.shopier.com/48901857"
    },
    {
        "id": "48901856",
        "title": "Grammarly Pro (1 Haftalık) - Kendi Hesabınıza",
        "price": "79,90 TL",
        "category": "ai",
        "is_vitrin": False,
        "showcase": False,
        "badge": "✨ ÖZEL LİSANS",
        "art_key": "grammarly",
        "rating": 4.9,
        "sales_count": 310,
        "delivery": "⚡ Anında Tanımlama",
        "warranty": "🛡️ Birebir Garanti",
        "desc": "Kendi Grammarly hesabınıza 7 günlük Premium davetiye tanımlaması.",
        "shopier_url": "https://www.shopier.com/48901856"
    },
    {
        "id": "48901852",
        "title": "Crunchyroll Özel Profil (1 Aylık)",
        "price": "59,90 TL",
        "category": "cinema",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🍥 ANİME CENNETİ",
        "art_key": "crunchyroll",
        "rating": 4.9,
        "sales_count": 560,
        "delivery": "⚡ Anında Otomatik Teslimat",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Sadece size ait PIN korumalı özel profil. En yeni animeleri Japonya yayınıyla eşzamanlı reklamsız izleyin.",
        "shopier_url": "https://www.shopier.com/48901852"
    },
    {
        "id": "48901851",
        "title": "Crunchyroll Ortak Hesap (1 Aylık)",
        "price": "39,90 TL",
        "category": "cinema",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🎌 ANİME İZLE",
        "art_key": "crunchyroll",
        "rating": 4.7,
        "sales_count": 420,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Ortak kullanımlı 1 aylık Mega Fan Crunchyroll hesabı. Çevrimdışı izleme ve HD anime keyfi.",
        "shopier_url": "https://www.shopier.com/48901851"
    },
    {
        "id": "la_netflix_ortak",
        "title": "Netflix 4K UHD (Ortak Profil)",
        "price": "59,90 TL",
        "category": "cinema",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🎬 4K UHD",
        "art_key": "netflix",
        "rating": 4.8,
        "sales_count": 2100,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "4K Ultra HD kalitesinde ekonomik ortak Netflix hesabı.",
        "shopier_url": "https://www.shopier.com/49002145"
    },
    {
        "id": "la_prime_ozel",
        "title": "Amazon Prime Video 4K (Özel Profil)",
        "price": "29,90 TL",
        "category": "cinema",
        "is_vitrin": False,
        "showcase": False,
        "badge": "📦 PRIME VİDEO",
        "art_key": "prime",
        "rating": 4.8,
        "sales_count": 890,
        "delivery": "⚡ Anında Teslimat",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Size özel PIN korumalı profil. The Boys, Rings of Power ve binlerce film 4K HDR kalitesinde.",
        "shopier_url": "https://www.shopier.com/49002144"
    },
    {
        "id": "la_hbo_ozel",
        "title": "HBO Max Özel Plan (1 Aylık Profil)",
        "price": "39,90 TL",
        "category": "cinema",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🐉 HBO MAX",
        "art_key": "hbo",
        "rating": 4.9,
        "sales_count": 940,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "House of the Dragon, Game of Thrones, The Last of Us ve Warner Bros sinema yapımları.",
        "shopier_url": "https://www.shopier.com/49002143"
    },
    {
        "id": "la_spotify_4m",
        "title": "Spotify Premium (4 Aylık Kod)",
        "price": "39,90 TL",
        "category": "social",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🎵 4 AY MÜZİK",
        "art_key": "spotify",
        "rating": 4.9,
        "sales_count": 830,
        "delivery": "⚡ Anında Kod Teslimi",
        "warranty": "🛡️ 4 Ay Tam Garanti",
        "desc": "4 Ay boyunca sınırsız müzik ve podcast deneyimi.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_steam_45",
        "title": "Steam 45$ Değerinde Random Key",
        "price": "19,90 TL",
        "category": "gaming",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🎲 ŞANS KEYİ",
        "art_key": "steam",
        "rating": 4.7,
        "sales_count": 1950,
        "delivery": "⚡ Anında Kod Teslimi",
        "warranty": "🛡️ Çalışma Garantili",
        "desc": "Minimum 45$ mağaza değerinde orijinal Steam oyun anahtarı.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_mc_purple_heart",
        "title": "Minecraft Purple Heart Cape Key",
        "price": "315,00 TL",
        "category": "gaming",
        "is_vitrin": True,
        "showcase": True,
        "badge": "💜 NADİR PELERİN",
        "art_key": "minecraft",
        "rating": 5.0,
        "sales_count": 420,
        "delivery": "⚡ Anında Key Teslimi",
        "warranty": "🛡️ Resmi Microsoft/Mojang Keyi",
        "desc": "Resmi Minecraft Twitch & TikTok 15. Yıl Özel Purple Heart Pelerini etkinleştirme kodu.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_mc_builder",
        "title": "Minecraft Builder Pelerini Keyi",
        "price": "8,00 TL",
        "category": "gaming",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🧱 MİNECRAFT KEY",
        "art_key": "minecraft",
        "rating": 4.8,
        "sales_count": 680,
        "delivery": "⚡ Anında Key Teslimi",
        "warranty": "🛡️ Orijinal Lisans",
        "desc": "Minecraft Builder pelerini aktivasyon kodu.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_mc_home",
        "title": "Minecraft Home Pelerini Keyi",
        "price": "10,00 TL",
        "category": "gaming",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🏡 MİNECRAFT KEY",
        "art_key": "minecraft",
        "rating": 4.8,
        "sales_count": 540,
        "delivery": "⚡ Anında Key Teslimi",
        "warranty": "🛡️ Orijinal Lisans",
        "desc": "Minecraft Home pelerini aktivasyon kodu.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_mc_copper",
        "title": "Minecraft Copper Pelerini Keyi",
        "price": "15,00 TL",
        "category": "gaming",
        "is_vitrin": False,
        "showcase": False,
        "badge": "🛡️ MİNECRAFT KEY",
        "art_key": "minecraft",
        "rating": 4.9,
        "sales_count": 460,
        "delivery": "⚡ Anında Key Teslimi",
        "warranty": "🛡️ Orijinal Lisans",
        "desc": "Minecraft Copper (Bakır) pelerini aktivasyon kodu.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_roblox_5offsale",
        "title": "5 Adet Offsale Roblox Hesap Paketi",
        "price": "29,90 TL",
        "category": "gaming",
        "is_vitrin": True,
        "showcase": True,
        "badge": "🧱 ROBLOX PAKET",
        "art_key": "roblox",
        "rating": 4.9,
        "sales_count": 780,
        "delivery": "⚡ 5 Hesap Bilgisi Anında Ekranda",
        "warranty": "🛡️ Giriş Garantili",
        "desc": "Artık satışta olmayan nadir (Offsale) eşyalara ve kıyafetlere sahip 5 adet Roblox hesap paketi.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_capcut_ortak",
        "title": "CapCut Pro (1 Aylık Ortak)",
        "price": "69,90 TL",
        "category": "design",
        "is_vitrin": False,
        "showcase": False,
        "badge": "✂️ EKONOMİK EDİT",
        "art_key": "capcut",
        "rating": 4.8,
        "sales_count": 910,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "CapCut Pro ortak hesabı. Tüm Pro filtreler, efektler ve export özellikleri açıktır.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_envato_kisisel",
        "title": "Envato Elements (1 Aylık Kişisel)",
        "price": "89,90 TL",
        "category": "design",
        "is_vitrin": True,
        "showcase": True,
        "badge": "💎 GRAFİK DEPOSU",
        "art_key": "envato",
        "rating": 4.9,
        "sales_count": 580,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Milyonlarca video şablonu, stok müzik, grafik ve WordPress temasına sınırsız indirme erişimi.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_freepik_kisisel",
        "title": "Freepik Premium (1 Aylık Kişisel)",
        "price": "89,90 TL",
        "category": "design",
        "is_vitrin": True,
        "showcase": True,
        "badge": "🎨 VEKTÖR & PSD",
        "art_key": "freepik",
        "rating": 4.9,
        "sales_count": 710,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Günde 100 Premium indirme hakkı, lisanslı vektörler, PSD'ler ve AI görsel oluşturucu.",
        "shopier_url": "https://www.shopier.com/49099018"
    },
    {
        "id": "la_adobe_cc_1m",
        "title": "Adobe Creative Cloud (1 Aylık Bireysel)",
        "price": "149,90 TL",
        "category": "design",
        "is_vitrin": False,
        "showcase": False,
        "badge": "⚡ FULL YETKİ",
        "art_key": "adobe",
        "rating": 4.9,
        "sales_count": 480,
        "delivery": "⚡ Anında Teslim",
        "warranty": "🛡️ 30 Gün Garanti",
        "desc": "Bireysel 1 aylık Adobe Creative Cloud lisansı.",
        "shopier_url": "https://www.shopier.com/48901859"
    },
    {
        "id": "la_office365",
        "title": "Office 365 Pro Plus Kişisel Hesap",
        "price": "69,90 TL",
        "category": "software",
        "is_vitrin": True,
        "showcase": True,
        "badge": "💼 OFİS YAZILIMI",
        "art_key": "office",
        "rating": 4.9,
        "sales_count": 1280,
        "delivery": "⚡ Anında Giriş Bilgileri",
        "warranty": "🛡️ 1 Yıl Lisans Garantisi",
        "desc": "Word, Excel, PowerPoint, Outlook ve 1TB / 5TB OneDrive depolama alanı içeren 5 cihaz lisansı.",
        "shopier_url": "https://www.shopier.com/48945472"
    },
    {
        "id": "la_windows_pro",
        "title": "Windows 10 / 11 Pro Orijinal Lisans Key",
        "price": "49,90 TL",
        "category": "software",
        "is_vitrin": True,
        "showcase": True,
        "badge": "💻 ÖMÜR BOYU KEY",
        "art_key": "windows",
        "rating": 5.0,
        "sales_count": 3100,
        "delivery": "⚡ 25 Haneli Key Anında Ekranda",
        "warranty": "🛡️ Ömür Boyu Orijinal Microsoft Lisansı",
        "desc": "Format sonrası dahi geçerli, 32/64 Bit tüm dillerle uyumlu orijinal Windows 10 & 11 Pro dijital aktivasyon anahtarı.",
        "shopier_url": "https://www.shopier.com/48945473"
    },
    {
        "id": "la_gmail_garantili",
        "title": "Gmail Hesap (3 Gün Garantili)",
        "price": "49,90 TL",
        "category": "social",
        "is_vitrin": False,
        "showcase": False,
        "badge": "📧 DOĞRULANMIŞ",
        "art_key": "gmail",
        "rating": 4.8,
        "sales_count": 1460,
        "delivery": "⚡ Mail & Şifre & Kurtarma Kodu Anında",
        "warranty": "🛡️ 3 Gün İlk Giriş & Kapanmama Garantisi",
        "desc": "SMS doğrulaması yapılmış, temiz IP ile açılmış kullanıma hazır kaliteli Gmail hesabı.",
        "shopier_url": "https://www.shopier.com/49099018"
    }
]

# Compile final products list
final_products = []
seen_ids = set()

for item in RAW_CATALOG:
    pid = str(item["id"])
    if pid in seen_ids:
        continue
    seen_ids.add(pid)
    
    art_key = item.get("art_key", "")
    img_path = copied_cache.get(art_key, "assets/products/card_clean_instagram.jpg")
    
    final_products.append({
        "id": pid,
        "title": item["title"],
        "price": item["price"],
        "category": item["category"],
        "is_vitrin": item.get("is_vitrin", False),
        "showcase": item.get("showcase", False),
        "badge": item.get("badge", "POPÜLER"),
        "image": img_path,
        "rating": item.get("rating", 4.9),
        "sales_count": item.get("sales_count", 500),
        "delivery": item.get("delivery", "⚡ 7/24 Anında Teslimat"),
        "warranty": item.get("warranty", "🛡️ Orijinal Lisans Güvencesi"),
        "desc": item.get("desc", ""),
        "shopier_url": item.get("shopier_url", "")
    })

# Save to miniapp_lisansarena/products_db.json
output_file = LA_DIR / "products_db.json"
with open(output_file, "w", encoding="utf-8") as f:
    json.dump(final_products, f, ensure_ascii=False, indent=2)

print(f"\n[SUCCESS] LisansArena Catalog Built! Total Unique Products: {len(final_products)}")
print(f"Vitrin Products Count: {sum(1 for p in final_products if p['is_vitrin'])}")
